# General Parameters
use_scan_matching: true
use_scan_barycenter: true
minimum_travel_distance: 0.12
minimum_travel_heading: 0.122                  #in radians
scan_buffer_size: 1750
scan_buffer_maximum_scan_distance: 350.0
link_match_minimum_response_fine: 0.8
link_scan_maximum_distance: 5.0
loop_search_maximum_distance: 3.5
do_loop_closing: false
loop_match_minimum_chain_size: 50
loop_match_maximum_variance_coarse: 0.4     # gets squared later
loop_match_minimum_response_coarse: 0.7
loop_match_minimum_response_fine: 0.7

# Correlation Parameters - Correlation Parameters
correlation_search_space_dimension: 0.5
correlation_search_space_resolution: 0.025
correlation_search_space_smear_deviation: 0.05

# Correlation Parameters - Loop Closure Parameters
loop_search_space_dimension: 3.0
loop_search_space_resolution: 0.05
loop_search_space_smear_deviation: 0.1

# Scan Matcher Parameters
distance_variance_penalty: 0.3              # gets squared later
#angle_variance_penalty: 0.384                # 22 in degrees (gets converted to radians then squared)
#fine_search_angle_offset: 0.00384               # in degrees (gets converted to radians)
#coarse_search_angle_offset: 0.384       # in degrees (gets converted to radians)
#coarse_angle_resolution: 0.0384                # in degrees (gets converted to radians)
angle_variance_penalty: 0.523                # 30 in degrees (gets converted to radians then squared)
fine_search_angle_offset: 0.00523               # in degrees (gets converted to radians)
coarse_search_angle_offset: 0.523       # in degrees (gets converted to radians)
coarse_angle_resolution: 0.0523                # in degrees (gets converted to radians)
minimum_angle_penalty: 0.9
minimum_distance_penalty: 0.5
use_response_expansion: true
