#! /bin/sh
### BEGIN INIT INFO
# Provides:          rc.local
# Required-Start:    $all
# Required-Stop:
# Default-Start:     2 3 4 5
# Default-Stop:
# Short-Description: Run /etc/rc.local if it exist
### END INIT INFO

. /etc/profile.d/ros.sh

PATH=/sbin:/usr/sbin:/bin:/usr/bin:/opt/ros/indigo/bin

EXEC_FILE="/opt/ros/indigo/bin/start_pp.sh"

# . /lib/init/vars.sh
# . /lib/lsb/init-functions

do_start() {
	if [ -x $EXEC_FILE ]; then
	        [ "$VERBOSE" != no ] 
		$EXEC_FILE
		ES=$?
		[ "$VERBOSE" != no ]
		return $ES
	fi
}

case "$1" in
    start)
	do_start
        ;;
    restart|reload|force-reload)
        echo "Error: argument '$1' not supported" >&2
        exit 3
        ;;
    stop)
        ;;
    *)
        echo "Usage: $0 start|stop" >&2
        exit 3
        ;;
esac
