#ifndef __WAV_H__
#define __WAV_H__

#include <stdint.h>

typedef enum {
	WAV_WELCOME_ILIFE				= 1,
	WAV_PLEASE_START_CLEANING		= 2,
	WAV_CLEANING_FINISHED			= 3,
	WAV_CLEANING_START				= 4,
	WAV_CLEANING_WALL_FOLLOW		= 5,
	WAV_BACK_TO_CHARGER				= 6,
	WAV_CLEANING_SPOT				= 7,
	WAV_CLEANING_NAVIGATION			= 8,
	WAV_APPOINTMENT_DONE			= 9,
	WAV_VACCUM_MAX					= 10,
	WAV_BATTERY_LOW					= 11,
	WAV_BATTERY_CHARGE				= 12,
	WAV_BATTERY_CHARGE_DONE			= 13,
	WAV_ERROR_RUBBISH_BIN			= 14,
	WAV_CLEAN_RUBBISH_BIN			= 15,
	WAV_ERROR_LEFT_BRUSH			= 16,
	WAV_ERROR_RIGHT_BRUSH			= 17,
	WAV_ERROR_LEFT_WHEEL			= 18,
	WAV_ERROR_RIGHT_WHEEL			= 19,
	WAV_ERROR_MAIN_BRUSH			= 20,
	WAV_ERROR_SUCTION_FAN			= 21,
	WAV_ERROR_BUMPER				= 22,
	WAV_ERROR_CLIFF					= 23,
	WAV_ERROR_MOBILITY_WHEEL		= 24,
	WAV_ERROR_LIFT_UP				= 25,
	WAV_TEST_MODE					= 26,
	WAV_CAMERA_CALIBRATION_MODE		= 27,
	WAV_TEST_MODE_IEC				= 28,
	WAV_CAMERA_CALIBRATION_START	= 29,
	WAV_CAMERA_CALIBRATION_SUCCESS	= 30,
	WAV_CAMERA_CALIBRATION_FAIL		= 31,
	WAV_TEST_SUCCESS				= 32,
	WAV_TEST_FAIL					= 33,
	WAV_WIFI_CONNECTING				= 34,
	WAV_WIFI_CONNECTED				= 35,
	WAV_TEST_LIDAR					= 36,
	WAV_CLEANING_CONTINUE			= 37,
	WAV_SYSTEM_INITIALIZING			= 38,
	WAV_BACK_TO_CHARGER_FAILED		= 39,
	WAV_CLEANING_PAUSE				= 40,
	WAV_CLEAR_ERROR					= 41,
	WAV_CANCEL_APPOINTMENT			= 42,
	WAV_PLAN_CLEANING_START			= 43,
	WAV_CLEANING_STOP				= 44,
}WavType;

void wav_play(WavType action);
bool wav_open_pcm_driver(void);
void wav_close_pcm_driver(void);
void wav_launch_mixer(void);
void wav_adjust_volume(long volume);

#endif
